# Generated by Django 5.2 on 2025-09-02 14:47

import core.media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.media_path.user_media_image_path, verbose_name='Profile Image'),
        ),
    ]
