# Generated by Django 5.2 on 2025-08-18 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='Code')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify Email')], max_length=20, verbose_name='purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email code verification',
                'verbose_name_plural': 'Email codes verification',
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='users_email_user_id_d47694_idx')],
            },
        ),
    ]
