# Generated by Django 5.2 on 2025-09-03 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcodemodel',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify Email'), ('reset_password', 'Reset Password')], max_length=20, verbose_name='purpose'),
        ),
        migrations.CreateModel(
            name='ResetPasswordTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_used', '-created_at'], name='users_reset_user_id_c9deac_idx')],
            },
        ),
    ]
