# Generated by Django 5.2 on 2025-08-21 09:13

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailcodemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFAModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
                ('purpose', models.CharField(choices=[('Verfy phone', 'verify_phone'), ('Login 2FA', 'Login_2FA')], max_length=20, verbose_name='purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('is_mobile_verified', models.BooleanField(verbose_name='phone number verified?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Two Factor Authenticate Mobiles',
                'verbose_name_plural': 'Two Factor Authenticate Mobile',
            },
        ),
    ]
