# Generated by Django 5.2 on 2025-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_twofamodels'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='twofamodels',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='users_twofa_user_id_34b39e_idx'),
        ),
    ]
