# Generated by Django 5.2 on 2025-09-04 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailcodemodel_purpose_resetpasswordtokenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtokenmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
