# Generated by Django 5.2 on 2025-08-23 11:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_twofamodels_users_twofa_user_id_34b39e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofamodels',
            name='code',
            field=models.CharField(default='', max_length=128, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='twofamodels',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
