# Generated by Django 5.2 on 2025-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_resetpasswordtokenmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofamodels',
            name='purpose',
            field=models.CharField(choices=[('verify_phone', 'Verfy phone'), ('Login_2FA', 'Login 2FA'), ('Disable_2FA', 'Disable 2FA')], max_length=20, verbose_name='purpose'),
        ),
    ]
