# Generated by Django 5.2 on 2025-09-15 16:13

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_twofamodels_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='pendind_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='pending_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
