# Generated by Django 5.2 on 2025-08-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_twofamodels_code_alter_twofamodels_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofamodels',
            name='code',
            field=models.CharField(max_length=128, verbose_name='Code'),
        ),
    ]
