# Generated by Django 5.2 on 2025-09-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customusermodel_pendind_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='pendind_email',
            new_name='pending_email',
        ),
    ]
