# Generated by Django 5.2 on 2025-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_twofamodels_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofamodels',
            name='is_mobile_verified',
            field=models.BooleanField(default=False, verbose_name='phone number verified?'),
        ),
    ]
