# Generated by Django 5.2 on 2025-09-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_pendind_email_customusermodel_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_pending_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified?'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='pending_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='pending Email'),
        ),
        migrations.AlterField(
            model_name='emailcodemodel',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify Email'), ('change_email', 'Change Email')], max_length=20, verbose_name='purpose'),
        ),
    ]
