# Generated by Django 5.2 on 2025-09-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customusermodel_is_pending_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='pending Email'),
        ),
    ]
