# Generated by Django 5.2 on 2025-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customusermodel_pending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='pending Email'),
        ),
    ]
