# Generated by Django 5.2 on 2025-09-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customusermodel_pending_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_pending_email_verified',
        ),
    ]
