"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$4%s(8c*r@-8jrxoia6j)wx)qm+ria*^hn*m12(mhi+fu0x&%-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'drf_yasg',

    #phone_number_field
    'phonenumber_field',

    #apps
    'users.apps.UsersConfig',
]

AUTH_USER_MODEL = 'users.CustomUserModel'
EMAIL_CODE_VERIFICATION_EXPIRE_SECONDS = 300 # expire after 5 minute
CODE_RESEND_INTERVAL_SECONDS = 120 # حداقل فاصله بین ارسال های مجدد کد (rate limit)
VERIFY_EMAIL_CODE_MAX_ATTEMPTS = 3 # تعداد تلاش اشتباه وارد کردن کد 

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle', # برای هر ویو یک scope تعریف کنی
        # اگه تغریف نشه عملا هر چی توی DEFAULT_THROTTLE_RATES نوشتیم کار نمیکنه
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',     
        'user': '100/hour',
        'email_register': '2/minute',
        'email_verify': '5/minute',
        "resend_verification_code": "3/hour",
    }
   
}
# ---------- backends authentication ---------------
AUTHENTICATION_BACKENDS = [
    'users.backends.MultiFieldModelBackend',  # اولویت اول
    'django.contrib.auth.backends.ModelBackend',  # در صورت نیاز
]
# ----------------------------------------------------

# ---------- simple JWT -----------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=3600), # access token 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10), # refresh token
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,  #اگه کاربر از طریق jwt احراز هویت کنه  ازین طریق اخرین لاگینش به روز رسانی میشه در دیتابیس
}
# ---------------------------------------------------


# ---------------- default phone number field ------------------------
PHONENUMBER_DEFAULT_REGION = 'IR'
# --------------------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
